-- MySQL Script generated by MySQL Workbench
-- Wed Apr 15 14:52:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`laboratorio` (
  `idlaboratorio` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(5000) NOT NULL,
  PRIMARY KEY (`idlaboratorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `idinventario` INT NOT NULL AUTO_INCREMENT,
  `miligramos` INT NOT NULL,
  `names` VARCHAR(50) NOT NULL,
  `description` VARCHAR(5000) NOT NULL,
  `admissionDate` DATETIME NOT NULL,
  `expirationDate` DATETIME NOT NULL,
  `loteCode` VARCHAR(10) NOT NULL,
  `quantity` INT NOT NULL,
  `price` INT NOT NULL,
  `laboratorio_idlaboratorio` INT NULL,
  PRIMARY KEY (`idinventario`, `laboratorio_idlaboratorio`),
  INDEX `fk_inventario_laboratorio1_idx` (`laboratorio_idlaboratorio` ASC) VISIBLE,
  CONSTRAINT `fk_inventario_laboratorio1`
    FOREIGN KEY (`laboratorio_idlaboratorio`)
    REFERENCES `mydb`.`laboratorio` (`idlaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipoProducto` (
  `idtipoProducto` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idtipoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estante` (
  `idEstante` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`idEstante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ciudad` (
  `idciudad` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idciudad`, `Departamento_idDepartamento`),
  INDEX `fk_ciudad_Departamento1_idx` (`Departamento_idDepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `nit` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `ciudad_id` INT NOT NULL,
  PRIMARY KEY (`idproveedor`, `ciudad_id`),
  INDEX `fk_proveedor_ciudad1_idx` (`ciudad_id` ASC) VISIBLE,
  CONSTRAINT `fk_proveedor_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `mydb`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `tipoProducto_id` INT NOT NULL,
  `inventario_id` INT NOT NULL,
  `Estante_id` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`idproducto`, `tipoProducto_id`, `inventario_id`, `Estante_id`, `proveedor_id`),
  INDEX `fk_producto_tipoProducto1_idx` (`tipoProducto_id` ASC) VISIBLE,
  INDEX `fk_producto_inventario1_idx` (`inventario_id` ASC) VISIBLE,
  INDEX `fk_producto_Estante1_idx` (`Estante_id` ASC) VISIBLE,
  INDEX `fk_producto_proveedor1_idx` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_tipoProducto1`
    FOREIGN KEY (`tipoProducto_id`)
    REFERENCES `mydb`.`tipoProducto` (`idtipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_inventario1`
    FOREIGN KEY (`inventario_id`)
    REFERENCES `mydb`.`inventario` (`idinventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_Estante1`
    FOREIGN KEY (`Estante_id`)
    REFERENCES `mydb`.`Estante` (`idEstante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `mydb`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `rol_idrol` INT NOT NULL,
  `names` VARCHAR(45) NOT NULL,
  `lastNames` VARCHAR(45) NOT NULL,
  `documentType` VARCHAR(45) NOT NULL,
  `documentNumber` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `admissionDate` DATE NOT NULL,
  `age` INT NOT NULL,
  `birthDate` DATETIME NOT NULL,
  `points` INT NULL,
  `ciudad_id` INT NOT NULL,
  `departamento_id` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `rol_idrol`, `ciudad_id`, `departamento_id`),
  INDEX `fk_usuario_rol_idx` (`rol_idrol` ASC) VISIBLE,
  INDEX `fk_usuario_ciudad1_idx` (`ciudad_id` ASC, `departamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `mydb`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_ciudad1`
    FOREIGN KEY (`ciudad_id` , `departamento_id`)
    REFERENCES `mydb`.`ciudad` (`idciudad` , `Departamento_idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`farmacia` (
  `idfarmacia` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `logo` VARCHAR(5000) NOT NULL,
  `nit` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idfarmacia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`factura` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  `farmacia_id` INT NOT NULL,
  PRIMARY KEY (`idfactura`, `usuario_id`, `rol_id`, `farmacia_id`),
  INDEX `fk_factura_usuario1_idx` (`usuario_id` ASC, `rol_id` ASC) VISIBLE,
  INDEX `fk_factura_farmacia1_idx` (`farmacia_id` ASC) VISIBLE,
  CONSTRAINT `fk_factura_usuario1`
    FOREIGN KEY (`usuario_id` , `rol_id`)
    REFERENCES `mydb`.`usuario` (`idusuario` , `rol_idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_farmacia1`
    FOREIGN KEY (`farmacia_id`)
    REFERENCES `mydb`.`farmacia` (`idfarmacia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  `factura_id` INT NOT NULL,
  `saleDate` DATETIME NOT NULL,
  `quantity` INT NOT NULL,
  `saleTotal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idventa`, `usuario_id`, `rol_id`, `factura_id`),
  INDEX `fk_venta_usuario1_idx` (`usuario_id` ASC, `rol_id` ASC) VISIBLE,
  INDEX `fk_venta_factura1_idx` (`factura_id` ASC) VISIBLE,
  CONSTRAINT `fk_venta_usuario1`
    FOREIGN KEY (`usuario_id` , `rol_id`)
    REFERENCES `mydb`.`usuario` (`idusuario` , `rol_idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `mydb`.`factura` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalleVenta` (
  `iddetalleVenta` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NOT NULL,
  `tipoProducto_id` INT NOT NULL,
  `inventario_id` INT NOT NULL,
  `Estante_id` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  `venta_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`iddetalleVenta`, `producto_id`, `tipoProducto_id`, `inventario_id`, `Estante_id`, `proveedor_id`, `venta_id`, `usuario_id`, `rol_id`),
  INDEX `fk_detalleVenta_producto1_idx` (`producto_id` ASC, `tipoProducto_id` ASC, `inventario_id` ASC, `Estante_id` ASC, `proveedor_id` ASC) VISIBLE,
  INDEX `fk_detalleVenta_venta1_idx` (`venta_id` ASC, `usuario_id` ASC, `rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalleVenta_producto1`
    FOREIGN KEY (`producto_id` , `tipoProducto_id` , `inventario_id` , `Estante_id` , `proveedor_id`)
    REFERENCES `mydb`.`producto` (`idproducto` , `tipoProducto_id` , `inventario_id` , `Estante_id` , `proveedor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleVenta_venta1`
    FOREIGN KEY (`venta_id` , `usuario_id` , `rol_id`)
    REFERENCES `mydb`.`venta` (`idventa` , `usuario_id` , `rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
