-- MySQL Script generated by MySQL Workbench
-- Fri Apr  3 12:11:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `idRol` INT NOT NULL,
  `description` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `names` VARCHAR(45) NOT NULL,
  `lastNames` VARCHAR(45) NOT NULL,
  `documentType` INT NOT NULL,
  `documentNumber` INT NOT NULL,
  `gender` INT NOT NULL,
  `admissionDate` DATE NOT NULL,
  `age` INT NOT NULL,
  `rol` INT NOT NULL,
  PRIMARY KEY (`id`, `rol`),
  INDEX `rol_id` (`rol` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Rol`
    FOREIGN KEY (`rol`)
    REFERENCES `mydb`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DELIMITER//
CREATE FUNCTION saveemployee(
    id INT,
    vnames VARCHAR(45),
    vlastNames VARCHAR(45),
    vdocumentType INT,
    vdocumentNumer INT,
    vgender INT,
    vadmissionDate DATE,
    vage INT,
    vrol INT
) RETURNS INT(1) READS SQL DATA DETERMINISTIC COMMENT 'Funcion que almacena un empleado' BEGIN
    DECLARE res INT DEFAULT 0; IF NOT EXISTS(
        SELECT
            employee
        FROM
            employee
        WHERE
            employee = vemployee
    ) THEN
INSERT INTO employee(
    NAMES,
    lastNames,
    documentType,
    documentNumber,
    gender,
    admissionDate,
    age,
    rol
)
VALUES(
    vnames,
    vlastNames,
    vdocumentType,
    vdocumentNumer,
    vgender,
    admissionDate,
    vage,
    vrol
);
SET
    res = 1;
END IF; RETURN res;
END//
DELIMITER ;
